apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: artgallery
type: Opaque
stringData:
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: artgallery
  DB_USER: postgres
  DB_PASSWORD: admin123    # "CHANGE_ME"
  DB_HOST: db
  DB_PORT: "5432"

  DEBUG: "False"

  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,192.168.56.13"

  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://192.168.56.13:3000"

  CSRF_TRUSTED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000,http://192.168.56.13:8000,http://localhost:3000,http://127.0.0.1:3000,http://192.168.56.13:3000,http://localhost:8081,http://127.0.0.1:8081,http://192.168.56.13:8081"

  SECRET_KEY: "django-insecure-j=yf1hrma2xdf$e=3c&13a462$#n+)m&=@*&wzhvduebqy#zpx"  # "CHANGE_ME"