apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: artgallery
type: Opaque
stringData:
  POSTGRES_DB: artgallery
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123   #"CHANGE_ME"