server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    # Django static files
    location /static/ {
        alias /app/staticfiles/;
    }

    # Django media files
    location /media/ {
        alias /app/media/;
    }

    # Django API
    location /api/ {
        proxy_pass http://backend:8000;
    }

    # Django admin
    location /admin/ {
        proxy_pass http://backend:8000;
    }

    # Next.js
    location / {
        proxy_pass http://frontend:3000;
    }
}

